package gui;


import com.mycompany.practica2.Motociclista;
import com.mycompany.practica2.Orden;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;


/**
 *
 * @author Usuario
 */
public class EnvioPedidosJFrame extends javax.swing.JFrame {
    private RestauranteMainFrame restauranteMainFrame;
    private MovimientoImagen movimientoImagen;
    private Orden ordenEnCurso;
    private boolean enviarMotociclista1Habilitado = true;
    private boolean enviarMotociclista2Habilitado = true;
    private boolean enviarMotociclista3Habilitado = true;
    
    
    
    public void setRestauranteMainFrame(RestauranteMainFrame restauranteMainFrame) {
    this.restauranteMainFrame = restauranteMainFrame;
}
    public Motociclista getMotociclistaAsignado() {
    if (ordenEnCurso != null) {
        return ordenEnCurso.getMotociclistaAsignado();
        }
        return null;
    }

    
    public EnvioPedidosJFrame() {
        initComponents();
        
        int rojo = 249; // Valor de rojo (0-255)
        int verde = 243; // Valor de verde (0-255)
        int azul = 204;
        Color colorPersonalizado = new Color(rojo, verde, azul);
        this.getContentPane().setBackground(colorPersonalizado);
        
        setVisible(true);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Delivery de Pedidos");
        System.out.println("Se reconoce el panel");
        
        movimientoImagen = new MovimientoImagen();

        
        enviarMotociclista1Button.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Iniciar el Timer para el movimiento de la imagen
            movimientoImagen.iniciarMovimiento();
        }
        });
    
    }
    
    public void iniciarOrden(Orden orden) {
    // Asigna la orden en curso
    this.ordenEnCurso = orden;
    movimientoImagen.iniciarMovimiento();
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enviarTodosButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enviarMotociclista1Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enviarMotociclista2Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        enviarMotociclista3Button = new javax.swing.JButton();
        regresarButton = new javax.swing.JButton();
        movimientoImagen1 = new gui.MovimientoImagen();
        movimientoImagen2 = new gui.MovimientoImagen();
        movimientoImagen3 = new gui.MovimientoImagen();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Visualización de Trayectorias");

        enviarTodosButton.setText("Enviar Todos");
        enviarTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarTodosButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Motocicleta 1");

        jLabel3.setText("Distancia");

        enviarMotociclista1Button.setText("Enviar");
        enviarMotociclista1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMotociclista1ButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Motocicleta 2");

        jLabel5.setText("Distancia");

        enviarMotociclista2Button.setText("Enviar");
        enviarMotociclista2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMotociclista2ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Motocicleta 3");

        jLabel7.setText("Distancia");

        enviarMotociclista3Button.setText("Enviar");
        enviarMotociclista3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMotociclista3ButtonActionPerformed(evt);
            }
        });

        regresarButton.setText("Regresar");
        regresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout movimientoImagen1Layout = new javax.swing.GroupLayout(movimientoImagen1);
        movimientoImagen1.setLayout(movimientoImagen1Layout);
        movimientoImagen1Layout.setHorizontalGroup(
            movimientoImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        movimientoImagen1Layout.setVerticalGroup(
            movimientoImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout movimientoImagen2Layout = new javax.swing.GroupLayout(movimientoImagen2);
        movimientoImagen2.setLayout(movimientoImagen2Layout);
        movimientoImagen2Layout.setHorizontalGroup(
            movimientoImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        movimientoImagen2Layout.setVerticalGroup(
            movimientoImagen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout movimientoImagen3Layout = new javax.swing.GroupLayout(movimientoImagen3);
        movimientoImagen3.setLayout(movimientoImagen3Layout);
        movimientoImagen3Layout.setHorizontalGroup(
            movimientoImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        movimientoImagen3Layout.setVerticalGroup(
            movimientoImagen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regresarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(209, 209, 209)
                        .addComponent(enviarTodosButton)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enviarMotociclista3Button)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enviarMotociclista2Button)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(enviarMotociclista1Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(movimientoImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                                    .addComponent(movimientoImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                                    .addComponent(movimientoImagen3, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))))
                        .addGap(0, 51, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(enviarTodosButton)
                    .addComponent(regresarButton))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22)
                                .addComponent(enviarMotociclista1Button))
                            .addComponent(movimientoImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(enviarMotociclista2Button))
                    .addComponent(movimientoImagen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(enviarMotociclista3Button))
                    .addComponent(movimientoImagen3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarMotociclista1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMotociclista1ButtonActionPerformed
        if (enviarMotociclista1Habilitado) {
            movimientoImagen1.iniciarMovimiento();
            enviarMotociclista1Habilitado = false;
            enviarMotociclista2Habilitado = true;
            enviarMotociclista3Habilitado = true;
        }
    }//GEN-LAST:event_enviarMotociclista1ButtonActionPerformed

    private void enviarMotociclista2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMotociclista2ButtonActionPerformed
        if (enviarMotociclista2Habilitado) {
            movimientoImagen2.iniciarMovimiento();
            enviarMotociclista1Habilitado = true;
            enviarMotociclista2Habilitado = false;
            enviarMotociclista3Habilitado = true;
        }
    }//GEN-LAST:event_enviarMotociclista2ButtonActionPerformed

    private void enviarMotociclista3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMotociclista3ButtonActionPerformed
        if (enviarMotociclista3Habilitado) {
            movimientoImagen3.iniciarMovimiento();
            enviarMotociclista1Habilitado = true;
            enviarMotociclista2Habilitado = true;
            enviarMotociclista3Habilitado = false;
        }
    }//GEN-LAST:event_enviarMotociclista3ButtonActionPerformed

    private void regresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarButtonActionPerformed
        dispose();

        if (restauranteMainFrame != null) {
            restauranteMainFrame.setVisible(true);
        }
    }//GEN-LAST:event_regresarButtonActionPerformed

    private void enviarTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarTodosButtonActionPerformed
        movimientoImagen1.iniciarMovimiento();
        movimientoImagen2.iniciarMovimiento();
        movimientoImagen3.iniciarMovimiento();

        // Deshabilitar los botones individuales
        enviarMotociclista1Habilitado = true;
        enviarMotociclista2Habilitado = true;
        enviarMotociclista3Habilitado = true;
    }//GEN-LAST:event_enviarTodosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvioPedidosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvioPedidosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvioPedidosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvioPedidosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvioPedidosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarMotociclista1Button;
    private javax.swing.JButton enviarMotociclista2Button;
    private javax.swing.JButton enviarMotociclista3Button;
    private javax.swing.JButton enviarTodosButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private gui.MovimientoImagen movimientoImagen1;
    private gui.MovimientoImagen movimientoImagen2;
    private gui.MovimientoImagen movimientoImagen3;
    private javax.swing.JButton regresarButton;
    // End of variables declaration//GEN-END:variables
}
