package gui;

import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import java.awt.Image;


/**
 *
 * @author Usuario
 */
public class PolloPanel extends javax.swing.JPanel {
    private Image imagenPollo;
    /**
     * Creates new form PizzaPanel
     */
    public PolloPanel() {
        initComponents();
        
            try {
            imagenPollo = ImageIO.read(new File("C:/Users/Usuario/Downloads/fried-chicken.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
    
    
       
        }

@Override
        protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // Dibujar la imagen en el panel y redimensionarla
        if (imagenPollo != null) {
            int panelWidth = getWidth();
            int panelHeight = getHeight();
            g.drawImage(imagenPollo, 0, 0, panelWidth, panelHeight, this);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(171, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 94, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
